version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - server/.env
    restart: unless-stopped
    networks:
      - proyectonet

  frontend_nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - proyectonet

networks:
  proyectonet:

